### ISSUE TITLE
Client Hangs at Browser Window

### ISSUE THREAD

**Issue by awedjob** [decentraland/vr-client#1]
Successfully downloaded and installed apk:
Version 0.1 (1)
Aug 12, 2022 at 13:49
170.67 MB
![Q2DCL-client 00](https://user-images.githubusercontent.com/6596502/184552556-af795b3e-4e9d-4e35-bff5-da808f8e28b6.PNG)
Was not able to click on any of the connection options. The menu, smooth rotate, and quit are on a layer behind the browser window. I inadvertently clicked on something else and couldn't figure out how to get back to the wallet connect screen. 

![Q2DCL-client 02](https://user-images.githubusercontent.com/6596502/184552572-7e47dfb2-1559-43d1-b4b3-d3bcd776dc8b.PNG)
Now when I quit and reload the app, after loading all I see is a blurry Decentraland background and no options to connect a wallet. I shut down the Q2 and will be starting it up again shortly to attempt another start.

![Q2DCL-client 01](https://user-images.githubusercontent.com/6596502/184552581-0040bfbd-b234-4e4c-a0c1-14329600d86a.PNG)

**Comment by mr0ng** [comment]
@awedjob I believe these issues have been resolved in the latest build. Can you verify if the issues are resolved on your end? If so, we will close this issue.

**Comment by awedjob** [comment]
Yes. These issues are not present in the current build published Sept 30 2022.
