### ISSUE TITLE
Missaligned walking direction

### ISSUE THREAD

**Issue by EibrielInv** [decentraland/vr-client#2]
Hi, awesome work!

If looking at certain direction I try to go forward, the avatar go forward, but at the same time slightly to the side.

For example walking over narrow bridge, looking forward, pressing forward results in the avatar getting closer and closer to the edge and eventually falling over.

I need to look slightly to the side to cross a narrow bridge.

**Comment by mr0ng** [comment]
I believe this is a known issue with WMR headsets in SteamVR - and is on the list to be fixed. Can you confirm which device you were using?

**Comment by EibrielInv** [comment]
Hi, I was testing on Oculus 2 using the `.apk` that expired recently, the one with z ordering issues (didn't try the new `.apk`)
