### ISSUE TITLE
When Teleporting: Stuck on Loading

### ISSUE THREAD

**Issue by JonnyFiat** [decentraland/vr-client#3]
![com Decentraland DecentralandVR-20220814-223107](https://user-images.githubusercontent.com/93795449/184674096-0f4a2e55-2858-4403-a6ca-3efa24d4232c.jpg)

Actions taken:
From initial location, selected Menu, chose a new location and the loading screen got stuck (attached photo). I waited 5 minutes (approx.).

**Comment by mr0ng** [comment]
@JonnyFiat is this still an issue, or can we close this as resolved based on your tests in the latest builds?

**Comment by JonnyFiat** [comment]
@mr0ng Resolved on reboot.

**Comment by mr0ng** [comment]
Thank you - in that case, I'll close this issue for now. Feel free to re-open or open a new issue if you notice it again.
